version: "3.9"

services:
  db:
    image: postgres:16
    container_name: godentrenet_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: godentrenet
      POSTGRES_PASSWORD: godentrenet_pass
      POSTGRES_DB: godentrenet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - godentrenet_network

  redis:
    image: redis:7-alpine
    container_name: godentrenet_redis
    restart: unless-stopped
    command: redis-server --save "" --appendonly no
    networks:
      - godentrenet_network

  evolution:
    image: atendai/evolution-api:latest
    container_name: godentrenet_evolution
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      AUTHENTICATION_API_KEY: "sua_chave_global"
      SERVER_TYPE: "http"
      SERVER_PORT: "8080"
      SERVER_URL: "http://entrenet.tech:8080"
      DATABASE_ENABLED: "true"
      DATABASE_PROVIDER: "postgresql"
      DATABASE_CONNECTION_URI: "postgresql://godentrenet:godentrenet_pass@db:5432/godentrenet"
      DATABASE_CONNECTION_CLIENT_NAME: "evolution_api"
      CACHE_REDIS_ENABLED: "true"
      CACHE_REDIS_URI: "redis://redis:6379"
      CACHE_REDIS_PREFIX_KEY: "evolution"
      CACHE_REDIS_SAVE_INSTANCES: "false"
      QRCODE_LIMIT: "30"
      QRCODE_COLOR: "#198754"
      CONFIG_SESSION_PHONE_VERSION: "2.3000.1039171941"
      CONFIG_SESSION_PHONE_CLIENT: "Chrome"
      CONFIG_SESSION_PHONE_NAME: "Chrome"
      LOG_LEVEL: "ERROR,WARN,DEBUG,INFO,LOG,VERBOSE,DARK,WEBHOOKS"
      LOG_COLOR: "true"
      LOG_BAILEYS: "error"
      DEL_INSTANCE: "false"
      STORE_MESSAGES: "true"
      STORE_MESSAGE_UP: "true"
      STORE_CONTACTS: "true"
      STORE_CHATS: "true"
    volumes:
      - evolution_instances:/evolution/instances
    depends_on:
      - db
      - redis
    networks:
      - godentrenet_network

  migrate:
    image: node:20-alpine
    container_name: godentrenet_migrate
    working_dir: /app
    volumes:
      - .:/app
    environment:
      DATABASE_URL: "postgresql://godentrenet:godentrenet_pass@db:5432/godentrenet"
    command: sh -c "apk add --no-cache openssl && npm install --silent && npx prisma migrate deploy"
    depends_on:
      - db
    restart: "no"
    networks:
      - godentrenet_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: godentrenet_web
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://godentrenet:godentrenet_pass@db:5432/godentrenet"
      EVOLUTION_API_URL: "http://evolution:8080"
      EVOLUTION_API_KEY: "sua_chave_global"
      NEXT_PUBLIC_BASE_URL: "https://entrenet.tech"
    depends_on:
      - db
      - evolution
    networks:
      - godentrenet_network

  typebot-db:
    image: postgres:15
    container_name: godentrenet_typebot_db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=typebot
      - POSTGRES_PASSWORD=typebot_pass
    volumes:
      - typebot_data:/var/lib/postgresql/data
    networks:
      - godentrenet_network

  typebot-builder:
    image: baptistearno/typebot-builder:latest
    container_name: godentrenet_typebot_builder
    restart: unless-stopped
    ports:
      - "8081:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:typebot_pass@typebot-db:5432/typebot
      - NEXTAUTH_URL=http://entrenet.tech:8081
      - NEXT_PUBLIC_VIEWER_URL=http://entrenet.tech:8082
      - ADMIN_EMAIL=seu@email.com
      - ENCRYPTION_SECRET=minha_chave_secreta_typebot_1234
      - DISABLE_SIGNUP=false
      - SMTP_USERNAME=fake_user
      - SMTP_PASSWORD=fake_pass
      - SMTP_HOST=fake_host
      - NEXT_PUBLIC_SMTP_FROM=fake@email.com
      - GITHUB_CLIENT_ID=Ov23lix8QTWLdCV4x90u
      - GITHUB_CLIENT_SECRET=b5d80409eaa2d2437bdde6c80d80778b397dc883
    depends_on:
      - typebot-db
    networks:
      - godentrenet_network

  typebot-viewer:
    image: baptistearno/typebot-viewer:latest
    container_name: godentrenet_typebot_viewer
    restart: unless-stopped
    ports:
      - "8082:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:typebot_pass@typebot-db:5432/typebot
      - NEXT_PUBLIC_VIEWER_URL=http://entrenet.tech:8082
      - ENCRYPTION_SECRET=minha_chave_secreta_typebot_1234
    depends_on:
      - typebot-db
    networks:
      - godentrenet_network

volumes:
  postgres_data:
  evolution_instances:
  typebot_data:

networks:
  godentrenet_network:
    driver: bridge
